name: Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: baixar código
        uses: actions/checkout@v6

      - name: configurar python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: instalar dependências
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: executar testes
        run: |
          python -m pytest -q
